[package]
name = "ina219"
description = "INA219 current/power monitor driver"
version = "0.2.0"
keywords = ["ina219", "driver", "i2c", "current", "no_std"]
repository = "https://github.com/scttnlsn/ina219"
authors = ["Scott Nelson <scott@scottnelson.co>"]
license = "MIT/Apache-2.0"


[dependencies]
byteorder = {version = "1.2.1", default-features = false}
embedded-hal = "0.2"

[dev-dependencies]
linux-embedded-hal = "0.2"
embedded-hal-mock = "0.4"
